# Generated by Django 4.2.4 on 2023-08-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postproductimage',
            old_name='prod',
            new_name='product',
        ),
    ]
