# Generated by Django 4.2.4 on 2023-08-15 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_prod_postproductimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postproductimage',
            old_name='product',
            new_name='prod',
        ),
    ]
